### ISSUE TITLE
Get access to nextcloud accounts

### ISSUE THREAD

**Issue by tobiasKaminsky** [nextcloud/Android-SingleSignOn#16]
Extracted from #11:
David:
> Another problem, which also affects case 1 is, that the FindAccounts will only return accounts that the user have granted access to (due to the new security restrictions on Android 8+)

Tobi:
> This is done when installing & using NC files app, or? As we require to first have NC files setup correctly, this should be no real problem, or?

David:
> As far as I understand, each account will be "private" or lets say not visible for any other app. The app has to use the android AccountManager.newChooseAccountIntent() method for each account before being able to access all accounts (and I think it's on a per account basis). I'll run some tests now.

Would be cool, if you have some idea on this :-)

**Comment by tobiasKaminsky** [comment]
@David-Development is this still true?

**Comment by David-Development** [comment]
I don't think so. On all the devices that I tested on (Android 7 and Android P) it worked perfectly. And this is due to the fact that we call the Android API to list all the accounts in the foreground (I think we won't be able to list them in the background if we don't have access to them) - but we don't really need that anymore since the single sign on library caches it :)

(Just verified it again on Android P)
