### ISSUE TITLE
Offer users the choice where to install the app from

### ISSUE THREAD

**Issue by rugk** [nextcloud/Android-SingleSignOn#25]
Seeing the screencast I noticed you give the user the PlayStore URL.

IMHO this is not good, because users may want to use F-Droid.

However, AFAIK you can just use the app ID and pass that to some intend and then users can actually select the appstore they want to get the app from. (I've seen this in other apps.)

**Comment by rugk** [comment]
BTW, this would also prevent that the PlayStore is opened in the web browser. :smile:

**Comment by David-Development** [comment]
Hmm.. where did you get that information from? 😄 Did I show some images somewhere? 

Actually it let's the user decide and only opens the browser if neither f-droid or google play store is installed. (in my original slides there were some screenshots from my emulator - without f-droid or play store, that's why it was opened in the browser)

Reference in code:
https://github.com/nextcloud/Android-SingleSignOn/blob/110b781699d21320a1a1be54b648db27dd035e4d/src/main/java/com/nextcloud/android/sso/helper/FilesAppNotInstalledHelper.java

**Comment by rugk** [comment]
The screencast in the Readme, as I've said.

**Comment by David-Development** [comment]
@rugk oh okay, I see. Yes that's because I recorded it on the emulator. As I'm still planning on doing some refactoring on the UI of the news app, I'll have to record a new video soon. Thanks for the hint!
