### ISSUE TITLE
Use LiveData in API

### ISSUE THREAD

**Issue by schaarsc** [nextcloud/Android-SingleSignOn#26]
this is more a question than an issue ...

I'm trying to become acquainted with this library and I have noticed that in the examples Observable is used as a return type. I was wondering why Observable was chosen instead of LiveData? LiveData is lifecycle aware, integrates nicely with ViewModel, Room, etc. and appears to be the recommended data type for data holders (https://developer.android.com/jetpack/docs/guide)

**Comment by David-Dev** [comment]
![image](https://user-images.githubusercontent.com/3943392/44660698-c5cff280-aa08-11e8-9b3d-82c3939021e9.png)

**Comment by desperateCoder** [comment]
We use LiveData in the Deck-app a lot. I have some methods written, that could come handy, when you are going to implement the support: https://github.com/stefan-niedermann/nextcloud-deck/blob/master/app/src/main/java/it/niedermann/nextcloud/deck/persistence/sync/adapters/db/util/LiveDataHelper.java

e.g. you can turn anything into a LiveData and stuff. Maybe this helps. If you have questions about it, you know how to contact me :wink:

**Comment by stefan-niedermann** [comment]
AFAIK it is not possible to make network requests directly via `LiveData`. One would need to perform the actual `Call`s and map them into a new `MutableLiveData` instance - or transform an `Observable` into `LiveData`.

My understanding of a [good Android app architecture](https://developer.android.com/jetpack/guide#overview) is, that the `Repository` layer is responsible of delivering results from a local store (aka database) and synchronizing the contents of the database with unreliable remote resources in the background.
`LiveData` is therefore understandable needed to watch the data of a database via repository, but since the synchronization with remote sources should be handled in the background, there is no dependency to the current state of the `Activity` / `Fragment` here in my opinion.

@schaarsc are you aware of any app which is using `LiveData` in the `Remote Data Source` layer? Maybe i am missing something here, but i have never seen something like this in the wild yet.

However, i think a valid point is to make the current `SingleSignOnAccount` available as a `LiveData` which then can be used in combination with `Transformations#map` or `Transformations#switchMap`. I therefore created [a PR](https://github.com/nextcloud/Android-SingleSignOn/pull/415) which adds this feature and deprecates the usage of `(un)registerSharedPreferenceChangeListener`.

**Comment by schaarsc** [comment]
I have not been active for quite some time, so I'm not sure how this would fit into the current state of implementations ...

The idea behind the original request was to handle all data with LiveData (local and remote).
The UI would be connected to MediatorLiveData and does not need to know where the data comes from.

References:
- https://developer.android.com/jetpack/guide#addendum
- https://developer.android.com/topic/libraries/architecture/livedata#merge_livedata
