### ISSUE TITLE
Methods are not supprted, trying to implement webdav (propfind)

### ISSUE THREAD

**Issue by PhieF** [nextcloud/Android-SingleSignOn#41]
Hi,

I get a com.nextcloud.android.sso.exceptions.NextcloudUnsupportedMethodException when using propfind to list a directory in nextcloud

I don't think there is another way to implement it so... because the lib to me to contact devs of this lib and not of the android app, here I am :)

Would it be possible to add some methods such as the propfind one ?

Thanks :)

**Comment by AndyScherzinger** [comment]
Hi @PhieF I'd expect any server calls that aren't related to the thr account itself and thus SSO to be rather found or placed in the general Nextcloud Android client lib here: https://github.com/nextcloud/android-library

Pinging @tobiasKaminsky :)

**Comment by David-Development** [comment]
Hello @PhieF, it wasn't added originally because the Apache Library that the nextcloud files app is using doesn't support it right away. Did you test the added `PROPFIND` method yet? Other than that, it looks good to me! (It might be better to place it inside the android-library project as @AndyScherzinger mentioned)

**Comment by tobiasKaminsky** [comment]
Let us continue in library repo for this.
