### ISSUE TITLE
Please allow MKCOL requests

### ISSUE THREAD

**Issue by MTRNord** [nextcloud/Android-SingleSignOn#43]
Hi I am trying to make a App that doesnt need a Server Side app and simply uses a json file to save the data (Simply because I dont want to and dont have the time to code an App and I dont want my users to add a App that only handles one json file).

I want to save this json inside a folder to keep the users root clean. But to be able to create a folder I need to do a MKCOL request but trying that I get a `EXCEPTION_UNSUPPORTED_METHOD` error. Is there a workaround to do that request anyway?

**Comment by tobiasKaminsky** [comment]
You can use the NC android library, there is a CreateFolderRemoteOperation.

**Comment by David-Development** [comment]
@MTRNord thanks for showing interest in this library.

There is a way to make a `MKCOL` request. However this feature was added recently by @PhieF and was merged into master about 5 hours ago. In order to use this feature yet, you'll have to build the nextcloud-files app yourself (master branch). After that, update this library to the following version:
```gradle
implementation 'com.github.nextcloud:Android-SingleSignOn:0.2.0'
```

Please make sure to include a version check in your app as your app will require the nextcloud files app to be installed in version 3.5 or higher. (https://github.com/nextcloud/Android-SingleSignOn#additional-info)


More information on the implementation / Pull-Request can be found here: 
https://github.com/nextcloud/android/pull/3428
and here:
https://github.com/nextcloud/Android-SingleSignOn/pull/42

**Comment by MTRNord** [comment]
@David-Development thanks that is awesome!

@tobiasKaminsky I actually just migrated away from that as I didn't want to worry too much about the user Management.
