### ISSUE TITLE
Library doesn't recognize the Nextcloud Dev app

### ISSUE THREAD

**Issue by strugee** [nextcloud/Android-SingleSignOn#46]
STR:

1. Install Nextcloud Dev
2. Install Nextcloud News
3 Try to use the SSO option in News

You'll get a message asking you to install the files app, even though the development version is already installed. I'm assuming this is the right place for this issue but I'm happy to refile in the downstream News issue tracker if that's the right place.

**Comment by David-Development** [comment]
Thanks for the feedback. Yes, this is the right place. Indeed, this shouldn't happen.. It shouldn't matter if you have the dev version or the one from google play. 

Couple of questions for you:
- What Android Version are you on?
- Did you compile the nextcloud dev version yourself? 
- What version of the nextcloud news app are you using?

**Comment by strugee** [comment]
I'm on LineageOS 15.1 (Android 8.1). Both apps are installed from F-Droid. News version is 0.9.9.25.

**Comment by David-Development** [comment]
@strugee Thank you :) 

@tobiasKaminsky the problem is, that we don't support the dev version yet. As the package is different from (`com.nextcloud.client`), the sso library won't pick up its existence. 

Is this something we should support? If yes, how do we handle it if both apps are installed and the user configured different accounts in each app? Or the same account? 

Problematic snippets:
https://github.com/nextcloud/Android-SingleSignOn/blob/82bbca0e8ff79eb0cf5690096d84f5c5a7def26a/src/main/java/com/nextcloud/android/sso/AccountImporter.java#L68

https://github.com/nextcloud/Android-SingleSignOn/blob/82bbca0e8ff79eb0cf5690096d84f5c5a7def26a/src/main/java/com/nextcloud/android/sso/helper/VersionCheckHelper.java

**Comment by tobiasKaminsky** [comment]
> Is this something we should support? 

If that is not too much work, why not…

> If yes, how do we handle it if both apps are installed and the user configured different accounts in each app? Or the same account?

When querying & displaying the accounts we then would need to check on both apps and should add (dev) to the dev version accounts.

Accounts from dev and stable app which point to the same user (e.g. tobias@cloud.example.com) should then be distinguished.

**Comment by strugee** [comment]
Closing since #63 got merged and 0.4.0 went out with (according to the GitHub release notes) support for this. If that's not right feel free to reopen! Thanks :thumbsup:
