### ISSUE TITLE
OCS-API: Capabilities: CSRF check failed

### ISSUE THREAD

**Issue by desperateCoder** [nextcloud/Android-SingleSignOn#69]
Hey buddies!

Here my promised issue:
While this works fine:
``` bash
$ curl https://bestUser:superSecurePW@nextcloud.fancyDomain.com/ocs/v2.php/cloud/capabilities?format=json -H 'OCS-APIRequest: true' 
```
Using the Retrofit API builder with the following Endpoint definiton doesn't:
``` JAVA
@Headers({
        "OCS-APIRequest: true"
})
@GET("cloud/capabilities?format=json")
Observable<Capabilities> getCapabilities();
```
The result is always the following:
```
Caused by: java.lang.Throwable: {"message":"CSRF check failed"}
```
Same for calling the API without Retrofit:
``` JAVA
Map<String, String> params = new HashMap<>();
params.put("format", "json");

Map<String, List<String>> header = new HashMap<>();
header.put("OCS-APIRequest", Collections.singletonList( "true"));

NextcloudRequest nextcloudRequest = new NextcloudRequest.Builder()
            .setMethod("GET")
            .setUrl("/ocs/v2.php/cloud/capabilities")
            .setParameter(params)
            .setHeader(header)
            .build();
```
Have a look in the ApiProvider in the `dev/nc_api` branch of the Deck app:

https://github.com/stefan-niedermann/nextcloud-deck/blob/dev/nc_api/app/src/main/java/it/niedermann/nextcloud/deck/api/ApiProvider.java

The API is initialized there. I can't find any errors here... Feel free to check out the branch and test it yourself.

**Comment by burningthumb** [comment]
I ran this code (without Retrofit) and it threw the exception:

> The 'OCS-APIREQUEST' header will be automatically added by the Nextcloud SSO Library. Please remove the header before making a request

So I changed it as follows:

```
NextcloudRequest nextcloudRequest = new NextcloudRequest.Builder()
            .setMethod("GET")
            .setUrl("/ocs/v2.php/cloud/capabilities")
            .setParameter(params)
// comment out            .setHeader(header)
            .build();
```

And it worked for me.

**Comment by David-Development** [comment]
@burningthumb Thanks for testing this on your end! 

That seems about right. Since Rob already tested the request, I remember adding this check to the nextcloud side in order to prevent users setting this flag twice as it should be present on all requests anyways.. (and setting it twice causes problems as far as I remember)

I'm not sure why you didn't get the same error message as Rob. I'm checking if the header is present using `equalsIgnoreCase` as seen here:
https://github.com/nextcloud/android/blob/8955709705a8ae937403b1102a1d11cccc6b9258/src/main/java/com/nextcloud/android/sso/InputStreamBinder.java#L286

Which version of the nextcloud files app are you using? Maybe it's an outdated version? The feature was added on the 21st of may (and released sometime after that).

**Comment by desperateCoder** [comment]
Indeed, it also works with the Retrofit request builder, just by removing the header...

Also, my nextcloud app on my virtual device was quite outdated, so you were both right! So thanks @burningthumb and @David-Development! Works like a charm now!

**Comment by desperateCoder** [comment]
Oh, one more thing: after the update of the Nextcloud app i got the same message as @burningthumb.

**Comment by tobiasKaminsky** [comment]
Nice, thanks @burningthumb for debugging :+1:
